name: Daily Contributions

on:
  schedule:
    - cron: '0 12 * * 0-6'  # Runs Sunday-Saturday at noon UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  make-contribution:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config --global user.name "devv-leo"
          git config --global user.email "lekan.code@gmail.com"

      - name: Update contribution counter in README
        run: |
          # Find the current counter value
          if grep -qE "^Total contributions: [0-9]+" README.md; then
            count=$(grep -E "^Total contributions: [0-9]+" README.md | head -n 1 | grep -oE "[0-9]+")
            new_count=$((count+1))
            # Update the line with the new count
            sed -i "s/^Total contributions: [0-9]\+/Total contributions: ${new_count}/" README.md
          else
            # If not present, add it under the Contribution Counter section
            echo -e "\n## Contribution Counter\n\nTotal contributions: 1\n" >> README.md
          fi

      - name: Commit and push changes
        run: |
          git add README.md
          git commit -m "Increment counter" || exit 0
          git push origin main
